services:
  - type: web
    name: smartprep-ai-server
    env: docker
    dockerfilePath: ./server/Dockerfile
    dockerContext: ./server
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "8000"
      - key: ENV
        value: production
      - key: MONGO_ATLAS_URI
        sync: false
      - key: DB_NAME
        value: smartprep-ai
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_INDEX_NAME
        value: smartprep-ai
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
